CREATE TABLE IF NOT EXISTS `appointments` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_of_entry` date NOT NULL,
  `appointment_id` varchar(20) NOT NULL,
  `patient_id` varchar(50) DEFAULT NULL,
  `patient_name` varchar(255) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `is_vip` tinyint(1) NOT NULL DEFAULT 0,
  `priority` enum('Low','Normal','High','Urgent') DEFAULT 'Normal',
  `purpose_of_visit` varchar(255) DEFAULT NULL,
  `appointment_notes` text DEFAULT NULL,
  `dentist` varchar(150) DEFAULT NULL,
  `appointment_datetime` datetime NOT NULL,
  `status` enum('Pending','Confirmed','Complete','Cancelled','No Show','Rescheduled') NOT NULL DEFAULT 'Pending',
  `cancel_reason` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_appointments_appointment_id` (`appointment_id`),
  KEY `idx_appointments_patient_id` (`patient_id`),
  KEY `idx_appointments_datetime` (`appointment_datetime`),
  KEY `idx_appointments_status` (`status`),
  CONSTRAINT `fk_appointments_patient`
    FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
