CREATE TABLE IF NOT EXISTS `patient_medical_history` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` varchar(50) NOT NULL,
  `good_health` varchar(3) DEFAULT NULL,
  `under_treatment` varchar(3) DEFAULT NULL,
  `treatment_condition` text DEFAULT NULL,
  `serious_illness` varchar(3) DEFAULT NULL,
  `serious_illness_details` text DEFAULT NULL,
  `hospitalized` varchar(3) DEFAULT NULL,
  `hospitalized_reason` text DEFAULT NULL,
  `medication` varchar(3) DEFAULT NULL,
  `medication_details` text DEFAULT NULL,
  `tobacco` varchar(3) DEFAULT NULL,
  `alcohol_drugs` varchar(3) DEFAULT NULL,
  `allergic` varchar(3) DEFAULT NULL,
  `bleeding_time` varchar(100) DEFAULT NULL,
  `pregnant` varchar(3) DEFAULT NULL,
  `nursing` varchar(3) DEFAULT NULL,
  `birth_control` varchar(3) DEFAULT NULL,
  `blood_type` varchar(20) DEFAULT NULL,
  `blood_pressure` varchar(50) DEFAULT NULL,
  `allergies_json` longtext DEFAULT NULL,
  `conditions_json` longtext DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_patient_medical_history_patient_id` (`patient_id`),
  CONSTRAINT `fk_patient_medical_history_patient`
    FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
