CREATE TABLE IF NOT EXISTS treatment_services (
  service_id varchar(8) NOT NULL,
  service_name varchar(255) NOT NULL,
  category varchar(100) NOT NULL,
  item_id varchar(50) DEFAULT NULL,
  item_used varchar(255) DEFAULT NULL,
  appliance varchar(255) DEFAULT NULL,
  base_price decimal(12,2) NOT NULL DEFAULT 0.00,
  requires_tooth tinyint(1) NOT NULL DEFAULT 0,
  is_active tinyint(1) NOT NULL DEFAULT 1,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (service_id),
  KEY idx_treatment_services_category (category),
  KEY idx_treatment_services_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS treatments (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  treatment_id varchar(8) NOT NULL,
  patient_id varchar(50) DEFAULT NULL,
  patient_name varchar(255) DEFAULT NULL,
  service_id varchar(8) NOT NULL,
  treatment_date date NOT NULL,
  tooth_number varchar(100) DEFAULT NULL,
  other_treatments text DEFAULT NULL,
  description text DEFAULT NULL,
  item varchar(255) DEFAULT NULL,
  item_quantity int(10) unsigned NOT NULL DEFAULT 1,
  appliances varchar(255) DEFAULT NULL,
  amount decimal(12,2) NOT NULL DEFAULT 0.00,
  amount_charge decimal(12,2) NOT NULL DEFAULT 0.00,
  paid decimal(12,2) NOT NULL DEFAULT 0.00,
  payment_status enum('Paid','Partial','Unpaid') NOT NULL DEFAULT 'Unpaid',
  balance decimal(12,2) NOT NULL DEFAULT 0.00,
  dentist varchar(150) DEFAULT NULL,
  treatment_note text DEFAULT NULL,
  status enum('Scheduled','In Progress','Complete','Cancelled') NOT NULL DEFAULT 'Scheduled',
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (id),
  UNIQUE KEY uniq_treatments_treatment_id (treatment_id),
  KEY idx_treatments_patient_id (patient_id),
  KEY idx_treatments_service_id (service_id),
  KEY idx_treatments_date (treatment_date),
  KEY idx_treatments_status (status),
  KEY idx_treatments_payment_status (payment_status),
  CONSTRAINT fk_treatments_patient
    FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  CONSTRAINT fk_treatments_service
    FOREIGN KEY (service_id) REFERENCES treatment_services (service_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO treatment_services (service_id, service_name, category, requires_tooth)
VALUES
('228ce7c7', 'Composite Filling - Class 1', 'Restorative Treatment', 1),
('e2927e88', 'Composite Filling - Class 2', 'Restorative Treatment', 1),
('dcb1faef', 'Composite Filling - Class 3', 'Restorative Treatment', 1),
('59df6277', 'Composite Filling - Class 4', 'Restorative Treatment', 1),
('210a906f', 'Composite Filling - Class 5', 'Restorative Treatment', 1),
('88f175a8', 'Composite Filling - Class 6', 'Restorative Treatment', 1),
('747ae024', 'Indirect Filling - Inlays', 'Restorative Treatment', 1),
('707df6a0', 'Indirect Filling - Onlays', 'Restorative Treatment', 1),
('a63d5b57', 'Composite Veneers', 'Cosmetic Dental Procedure', 1),
('c42eb30d', 'Teeth Whitening', 'Cosmetic Dental Procedure', 0),
('5dd78589', 'CROWNS - PFM (Porcelain Fused to metal)', 'Prosthodontic Treatment', 1),
('32b36c5f', 'Fixed Bridge - PFM (Porcelain Fused to Metal)', 'Prosthodontic Treatment', 1),
('4541406b', 'Fixed Bridge - Emax', 'Prosthodontic Treatment', 1),
('ec2f23a3', 'Fixed Bridge - Zirconia', 'Prosthodontic Treatment', 1),
('5bc5b7d4', 'Fixed Bridge - Plastic / Temporary Crown', 'Prosthodontic Treatment', 1),
('3993cafd', 'Root Canal Therapy - 1st Visit', 'Endodontic Treatment', 1),
('28569d15', 'Root Canal Therapy - 2nd Visit', 'Endodontic Treatment', 1),
('2e33c6e8', 'Root Canal Therapy - 3rd Visit', 'Endodontic Treatment', 1),
('292f4ed8', 'Root Canal Therapy - 4th Visit', 'Endodontic Treatment', 1),
('61457bc8', 'Root Canal Therapy - 5th Visit', 'Endodontic Treatment', 1),
('9b7b1fae', 'Root Canal Therapy - Obturation', 'Endodontic Treatment', 1),
('94342997', 'Pulpotomy', 'Endodontic Treatment', 1),
('cc13be4c', 'Pulpectomy', 'Endodontic Treatment', 1),
('7c97f0ba', 'Simple Tooth Extraction', 'Oral Surgery', 1),
('2db6435d', 'Moderate Tooth Extraction', 'Oral Surgery', 1),
('8b1c4192', 'Severe Tooth Extraction', 'Oral Surgery', 1),
('b4b19483', 'Scaling & Polishing', 'Periodontal Treatment', 0)
ON DUPLICATE KEY UPDATE
  service_name = VALUES(service_name),
  category = VALUES(category),
  requires_tooth = VALUES(requires_tooth),
  updated_at = current_timestamp();
